### ISSUE TITLE
 GPL violations?

### ISSUE THREAD

**Issue by tnaoto** [oneops/sensor#4]
Sensor is Apache License v2.
But sensor use Esper is GPLv2.
I think sensor's License must be GPLv2.

example

https://github.com/oneops/sensor/blob/master/src/main/java/com/oneops/sensor/Sensor.java#L20
https://github.com/oneops/sensor/blob/master/src/main/java/com/oneops/sensor/listeners/ChannelDownListener.java#L22-L23

**Comment by schwankl** [comment]
@tnaoto we do not distribute or package esper with oneops, thus not in violation of GPLv2.

**Comment by tnaoto** [comment]
I dont think so.

SFS said

>This key dispute is whether or not non-GPL software can legally statically link or dynamically link to GPL libraries. Different opinions exist on this issue. The GPL is clear in requiring that all derivative works of code under the GPL must themselves be under the GPL. Ambiguity arises with regards to using GPL libraries, and bundling GPL software into a larger package (perhaps mixed into a binary via static linking). This is ultimately a question not of the GPL per se, but of how copyright law defines derivative works. 

https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

Do I have to release my code as GPL when a Java Library is GPL
http://opensource.stackexchange.com/questions/412/do-i-have-to-release-my-code-as-gpl-when-a-java-library-is-gpl
